# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgresthing

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    